In [1]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Lena\Downloads\customer_shopping_behavior_synthetic.csv")

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Frequency of Purchases
0,1,39,Female,Dress,Clothing,67,Massachusetts,M,Maroon,Fall,3.8,No,Bank Transfer,Standard,No,No,26,Fortnightly
1,2,52,Male,Jeans,Clothing,55,Hawaii,M,Black,Fall,2.9,No,Cash,2-Day Shipping,No,No,35,Monthly
2,3,49,Male,Belt,Accessories,49,Virginia,M,Red,Fall,3.9,Yes,Bank Transfer,Standard,Yes,Yes,37,Every 3 Months
3,4,50,Male,Boots,Footwear,32,Utah,L,Gold,Spring,2.5,No,Debit Card,Express,No,No,12,Annually
4,5,50,Male,Hat,Accessories,80,Mississippi,M,Navy,Summer,3.0,No,Venmo,Store Pickup,Yes,Yes,38,Fortnightly

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             10000 non-null  int64
 1   Age                     10000 non-null  int64
 2   Gender                  10000 non-null  str
 3   Item Purchased          10000 non-null  str
 4   Category                10000 non-null  str
 5   Purchase Amount (USD)   10000 non-null  int64
 6   Location                10000 non-null  str
 7   Size                    10000 non-null  str
 8   Color                   10000 non-null  str
 9   Season                  10000 non-null  str
 10  Review Rating           9905 non-null   float64
 11  Subscription Status     10000 non-null  str
 12  Payment Method          10000 non-null  str
 13  Shipping Type           10000 non-null  str
 14  Discount Applied        10000 non-null  str
 15  Promo Code Used         10000 non-null  str
 16  Previous Purchases      10000 non-null  int64
 17  Frequency of Purchases  10000 non-null  str
dtypes: float64(1), int64(4), str(13)
memory usage: 1.4 MB

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Payment Method,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Frequency of Purchases
count,10000.00000,10000.000000,10000,10000,10000,10000.000000,10000,10000,10000,10000,9905.000000,10000,10000,10000,10000,10000,10000.000000,10000
unique,NaN,NaN,2,25,4,NaN,50,4,20,4,NaN,2,6,6,2,2,NaN,7
top,NaN,NaN,Male,T-shirt,Clothing,NaN,New Hampshire,M,Green,Summer,NaN,No,Credit Card,Express,No,No,NaN,Monthly
freq,NaN,NaN,6738,594,6070,NaN,223,4383,543,2555,NaN,7218,1709,1746,5737,5737,NaN,1631
mean,5000.50000,43.859300,NaN,NaN,NaN,58.800700,NaN,NaN,NaN,NaN,3.719768,NaN,NaN,NaN,NaN,NaN,25.549500,NaN
std,2886.89568,13.941167,NaN,NaN,NaN,16.798059,NaN,NaN,NaN,NaN,0.558895,NaN,NaN,NaN,NaN,NaN,14.466329,NaN
min,1.00000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
25%,2500.75000,34.000000,NaN,NaN,NaN,47.000000,NaN,NaN,NaN,NaN,3.300000,NaN,NaN,NaN,NaN,NaN,13.000000,NaN
50%,5000.50000,44.000000,NaN,NaN,NaN,59.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,NaN,26.000000,NaN
75%,7500.25000,54.000000,NaN,NaN,NaN,70.000000,NaN,NaN,NaN,NaN,4.100000,NaN,NaN,NaN,NaN,NaN,38.000000,NaN
max,10000.00000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,50.000000,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             95
Subscription Status        0
Payment Method             0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Payment Method            0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Payment Method',
       'Shipping Type', 'Discount Applied', 'Promo Code Used',
       'Previous Purchases', 'Frequency of Purchases'],
      dtype='str')

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df = df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'promo_code_used',
       'previous_purchases', 'frequency_of_purchases'],
      dtype='str')

In [10]:
# create a column age_group
labels = ['Young Adult', 'Adult','Middle Age','Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [11]:
df[['age','age_group']].head(10)

   age    age_group
0   39        Adult
1   52   Middle Age
2   49   Middle Age
3   50   Middle Age
4   50   Middle Age
5   70       Senior
6   38        Adult
7   36        Adult
8   32  Young Adult
9   53   Middle Age

In [12]:
#create column purchase_frequency_days

frequency_mapping = {
    'Fortnightly':14,
    'Weekly': 7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping )

In [13]:
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       30                Monthly
2                       90         Every 3 Months
3                      365               Annually
4                       14            Fortnightly
5                      365               Annually
6                       90              Quarterly
7                       90              Quarterly
8                       14            Fortnightly
9                       14              Bi-Weekly

In [14]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0               No              No
1               No              No
2              Yes             Yes
3               No              No
4              Yes             Yes
5              Yes             Yes
6               No              No
7               No              No
8               No              No
9              Yes             Yes

In [15]:
#are these two values the same
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [16]:
df=df.drop('promo_code_used', axis = 1)

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'payment_method',
       'shipping_type', 'discount_applied', 'previous_purchases',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [18]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in C:\Users\Lena\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in C:\Users\Lena\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.1.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Lena\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
%pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in C:\Users\Lena\AppData\Local\Programs\Python\Python314\Lib\site-packages (1.2.3)
Requirement already satisfied: sqlalchemy in C:\Users\Lena\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.1.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Lena\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

user = "root"
password = quote_plus("1234")
host = "localhost"
port = 3306
database = "customer"

engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}")

df.to_sql("customer_behaviour", engine, if_exists="replace", index=False)

10000